### PR TITLE
Feature: Add NPM post-install scripts

### PR DESCRIPTION
**Pull request by pbnj**
Hi @IonicaBizau ,

Thank you for this lovely theme.
I contributed a feature that I hope you find helpful/useful.

I have added npm scripts that automatically get executed after the user installs the theme via npm.
Once the user types: `npm install --global flattiance`, npm will:
- create a local `.themes` directory in the current user's `$HOME` directory
- copy the `Flattiance` sub-directory into `$HOME/.themes`

I have also updated the README accordingly to inform users of the two current options for installing this theme.

I hope you find this Pull-Request beneficial.
If not, feel free to close it.

Let me know if you have any questions.

Thank you.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
This is amazing! 👍

**Comment by IonicaBizau** [comment]
I'll review it soon and merge it. Thanks! From a very quick view, it looks good!

**Comment by pbnj** [comment]
Worth mentioning: I've testing the npm scripts locally on my machine (e.g. `npm run postinstall:create-theme-dir && npm run postinstall:copy-theme`) and confirmed that it works locally.

**Comment by IonicaBizau** [comment]
It would be nice to `npm install flattiance -g` and bring the theme right there. Can you double-check if that works?

**Comment by IonicaBizau** [comment]
Actually I'll test it.

**Comment by pbnj** [comment]
Just discovered that `unity-tweak-tool` CLI gives you an option to start in "appearance" tab (aka Themes):

screenshot from 2017-04-26 00-28-12

So, you could potentially open the "Unity Tweak Tool" GUI straight to the Themes tab for the user to select the theme.

**Comment by pbnj** [comment]
I just added a 3rd post-install script:
```sh
if type unity-tweak-tool > /dev/null; then unity-tweak-tool -a; else echo 'Please, install unity-tweak-tool and manually activate Flattiance theme'; fi
```

**Pull request merged**
